AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  web-scrapping

Globals:
  Function:
    Timeout: 300
    MemorySize: 128


Resources:
  MyScrapyBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: webscrap-bucket

  httpApi:
    Type: AWS::Serverless::HttpApi
    Properties:  
      AccessLogSettings:
        DestinationArn: !GetAtt AccessLogs.Arn
        Format: $context.requestId
      CorsConfiguration:
        AllowOrigins: 
          - "*"
        AllowHeaders:
          - "*"
        AllowMethods:
          - GET
          - PUT
          - POST
          - OPTIONS
          - DELETE
      FailOnWarnings: True
  AccessLogs:
    Type: AWS::Logs::LogGroup


  MyScrapyFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.12
      CodeUri: web-scrapping/hello_world
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref MyScrapyBucket
      Environment:
        Variables:
          SCRAPY_S3_BUCKET: !Ref MyScrapyBucket

  MyQueryFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.query_handler
      Runtime: python3.12
      CodeUri: web-scraping/hello_world
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref MyScrapyBucket
      Environment:
        Variables:
          SCRAPY_S3_BUCKET: !Ref MyScrapyBucket
      Events:
        QueryApiEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref httpApi
            Method: POST
            Path: /query